#!/bin/bash

# Sync up git state
git fetch imac
git reset --hard imac/master

# Sync up uncommitted things
rsync -av 'pcarphin@192.168.2.15:~/Documents/GitHub/INF8480_TP2/*' .
ant

killall rmiregistry
sleep 1
CLASSPATH=bin rmiregistry &

./server_rpi 0 30 192.168.2.15 &

read

killall java
killall rmiregistry

